DROP TABLE IF EXISTS estimate_attachments,
estimate_lines,
products_and_services,
erpp_classes,
sync_histories,
preferences,
company_info,
estimates,
customers,
referrals,
crew_routes,
estimate_routes,
employees
